use student;
select * from details;
update details set address="korea" where id =6;
select * from details where address="kozhikode" OR address="korea";
alter table details add department varchar(25);
select * from details order by name desc;
select max(totalmarks) from details;
select min(totalmarks) from details;
select avg(computerscience) from details;
select sum(physics) from details;
update details set department="mathematics" where id=1;
update details set department="computer engineering" where id=2;
update details set department="mathematics" where id=3;
update details set department="physics" where id=4;
update details set department="computer science" where id=5;
update details set department="civil engineering" where id=6;
update details set department="physics" where id=7;
update details set department="biochemistry" where id=8;
update details set department="mech engineering" where id=9;
update details set department="mathematics" where id=10;
select * from details where department like '%g';
select * from details where name like 'a%';
alter table details drop column totalmarks;
alter table details add totalmarks int;
update details set totalmarks = maths+physics+computerscience;
alter table details add age int;
ALTER TABLE details add constraint age CHECK (age >= 18);
update details set age=20 where id=1;
update details set age=22 where id=2;
update details set age=21 where id=3;
update details set age=17 where id=4;
update details set age=18 where id=5;
update details set age=25 where id=6;
update details set age=22 where id=7;
update details set age=22 where id=8;
update details set age=20 where id=9;
update details set age=17 where id=10;
select * from details;
